/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafiles;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author aoosm
 */
public class Admin extends javax.swing.JFrame {

    public String Tid;
    public String Cemail;
    private String customerID;
    private String CID;
    /**
     * Creates new form Main
     */
    public Admin() {
        this("admin@admin.com");
    }

    public Admin(String email) {
        initComponents();
        //idInput.setBackground(new java.awt.Color(0,0,0,1));
        errNo.setVisible(false);  
        doneG.setVisible(false);
        this.Cemail = email;
        Account userP = new Account();
        userP.getAccInfo(Cemail);
        user.setText(userP.getFname());
    }
    public Admin(String email, String customerID){
        this(email);
        this.Tid = customerID;
        //jTabbedPane1.setSelectedIndex(3);
        idInput.setText(customerID);
        updateReservation();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconUser = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        mainTitle = new javax.swing.JLabel();
        subNav = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        nav = new javax.swing.JLabel();
        subNav1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idInput = new javax.swing.JTextField();
        doneG = new javax.swing.JLabel();
        generate = new javax.swing.JLabel();
        viewReservations = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        backInput = new javax.swing.JLabel();
        backSide = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        myreser = new javax.swing.JPanel();
        errNo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mainTitle1 = new javax.swing.JLabel();
        min1 = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        nav1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1545, 770));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_male_user_50px.png"))); // NOI18N
        jPanel1.add(iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 50, -1, 60));

        user.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("User");
        user.setToolTipText("");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 70, -1, 30));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Log Out.png"))); // NOI18N
        logout.setToolTipText("");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 60, -1, -1));

        mainTitle.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle.setText("Main Page");
        jPanel1.add(mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        subNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/sub-nav.png"))); // NOI18N
        jPanel1.add(subNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1560, -1));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/min.png"))); // NOI18N
        min.setToolTipText("");
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 20, 20, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_Close_30px_1.png"))); // NOI18N
        close.setToolTipText("");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 10, -1, 20));

        nav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/nav.png"))); // NOI18N
        nav.setToolTipText("");
        jPanel1.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, -1));

        subNav1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/sub-nav.png"))); // NOI18N
        jPanel1.add(subNav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1560, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idInput.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        idInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idInput.setToolTipText("");
        idInput.setBorder(null);
        idInput.setOpaque(true);
        jPanel2.add(idInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 102, 210, 30));

        doneG.setBackground(new java.awt.Color(0, 204, 0));
        doneG.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        doneG.setForeground(new java.awt.Color(0, 204, 0));
        doneG.setText("Generated Successfully");
        jPanel2.add(doneG, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 220, 30));

        generate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Genertate_Report.png"))); // NOI18N
        generate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateMouseClicked(evt);
            }
        });
        jPanel2.add(generate, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 190, 50));

        viewReservations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/view reservations.png"))); // NOI18N
        viewReservations.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewReservations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewReservationsMouseClicked(evt);
            }
        });
        jPanel2.add(viewReservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, 50));

        labelID.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        labelID.setForeground(new java.awt.Color(255, 255, 255));
        labelID.setText("Customer ID");
        labelID.setToolTipText("");
        jPanel2.add(labelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        backInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/inputID.png"))); // NOI18N
        backInput.setToolTipText("");
        jPanel2.add(backInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 230, 70));

        backSide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/side-back.png"))); // NOI18N
        jPanel2.add(backSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 380, -1));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));

        myreser.setBackground(new java.awt.Color(255, 255, 255));
        myreser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/errAdmin.png"))); // NOI18N
        myreser.add(errNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 520, 50));

        jTabbedPane1.addTab("tab3", myreser);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 1180, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTitle1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        mainTitle1.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle1.setText("Main Page");
        jPanel3.add(mainTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        min1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/min.png"))); // NOI18N
        min1.setToolTipText("");
        min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min1MouseClicked(evt);
            }
        });
        jPanel3.add(min1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 20, 20, -1));

        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_Close_30px_1.png"))); // NOI18N
        close1.setToolTipText("");
        close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });
        jPanel3.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 10, -1, 20));

        nav1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/nav.png"))); // NOI18N
        nav1.setToolTipText("");
        jPanel3.add(nav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void min1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseClicked

    }//GEN-LAST:event_min1MouseClicked

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked

    }//GEN-LAST:event_close1MouseClicked
    
    private void updateReservation(){
      /////////////////////////////////////////
        int vel = 0;
        int velC= 0;
        int noRows =0;
        int noRooms=0;
        int noMeals=0;
        /////////////////////////////////////////
        ReservationRooms[] reslistRooms = ReservationRooms.viewReservations(Tid);
         ReservationMeal[] reslistMeals = ReservationMeal.viewReservations(Tid);

        //////////////////////////////////////////
        //common 
      
        noRooms = reslistRooms.length;
        noMeals = reslistMeals.length;
         noRows = noRooms+noMeals;
        JLabel[] rowBack = new JLabel[noRows];
        JLabel[] cancelBtn = new JLabel[noRows];
        Meal mealTemp = new Meal();
        int mealCount = noMeals;
        int roomCount = noRooms;
        //System.out.println(reslist.length);
      if((reslistMeals.length+reslistRooms.length ) == 0){
            errNo.setVisible(true);
        }else{
          errNo.setVisible(false);
           }
              
           
    
        //roomCount = 3;
       // mealCount = 2;
        
        //room component 
        JLabel[] RoomName = new JLabel[roomCount];
        JLabel[] startDate = new JLabel[roomCount];
        JLabel[] endDate = new JLabel[roomCount];
        JLabel[] priceRoom = new JLabel[roomCount];
        //meals component
        JLabel[] restName = new JLabel[mealCount];
        JLabel[] noOfMeals = new JLabel[mealCount];
        JLabel[] mealName = new JLabel[mealCount];
        JLabel[] priceMeal = new JLabel[mealCount];
     
        int k =0;
        while(roomCount>0){
           RoomName[k] = new JLabel();
           startDate[k] = new JLabel();
           endDate[k] = new JLabel();
           priceRoom[k] = new JLabel();
           rowBack[k] =new JLabel();
           cancelBtn[k] = new JLabel();
        
           cancelBtn[k].setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Cancel.png"))); // NOI18N
           cancelBtn[k].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
           cancelBtn[k].setToolTipText("R" +" "+ reslistRooms[k].getRoomID());
           cancelBtn[k].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    cancelBtnMouseClicked(evt);
                }
            });
 	
           priceRoom[k].setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
           priceRoom[k].setForeground(new java.awt.Color(49, 50, 50));
           priceRoom[k].setText("Price: " + Double.toString(reslistRooms[k].getTotalPrice()));
           myreser.add(priceRoom[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40+velC, 180, 70));   

           endDate[k].setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
           endDate[k].setForeground(new java.awt.Color(22, 92, 122));
           endDate[k].setText("End Date: " + reslistRooms[k].getEndDate());
           myreser.add(endDate[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 63+velC, 230, -1)); 

           startDate[k].setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
           startDate[k].setForeground(new java.awt.Color(22, 92, 122));
           startDate[k].setText("Start Date: " + reslistRooms[k].getArrivalDate());
           myreser.add(startDate[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 55+velC, 230, 50));

           RoomName[k].setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
           RoomName[k].setForeground(new java.awt.Color(49, 50, 50));
           if(reslistRooms[k].getRoomID() == 1){
               RoomName[k].setText(reslistRooms[k].getNumberOfRooms() + "x Room A");
           }else if(reslistRooms[k].getRoomID() == 2){
               RoomName[k].setText(reslistRooms[k].getNumberOfRooms() + "x Room B");
           }else{
               RoomName[k].setText(reslistRooms[k].getNumberOfRooms() + "x Room C");
           }
           
            myreser.add(RoomName[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60+velC, 160, -1));
            myreser.add(cancelBtn[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40+velC, -1, 70));
            rowBack[k].setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/reserveRowBack.png"))); // NOI18N
            myreser.add(rowBack[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30+velC, 1110, 90));
            roomCount--;
            k++;
            velC+=100;
        }
      
       // velC -=100;
        int i =0;
        while(mealCount>0 ){
                restName[i] = new JLabel();
                noOfMeals[i] = new JLabel();
                mealName[i] = new JLabel();
                priceMeal[i] = new JLabel();
                rowBack[i] =new JLabel();
                cancelBtn[i] = new JLabel();
        
                cancelBtn[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Cancel.png"))); // NOI18N
                cancelBtn[i].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                cancelBtn[i].setToolTipText("M"+" "+ reslistMeals[i].getMealID());
                cancelBtn[i].addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        cancelBtnMouseClicked(evt);
                    }
                });
                
                priceMeal[i].setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                priceMeal[i].setForeground(new java.awt.Color(49, 50, 50));
                priceMeal[i].setText("Price: " + Double.toString(reslistMeals[i].getTotalPrice()));
                myreser.add(priceMeal[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40+velC, 180, 70));

                mealName[i].setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
                mealName[i].setForeground(new java.awt.Color(49, 50, 50));
                mealTemp.fillMealInfo(reslistMeals[i].getMealID());
                mealName[i].setText(mealTemp.getName());
                myreser.add(mealName[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60+velC, 160, 50));

                noOfMeals[i].setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
                noOfMeals[i].setForeground(new java.awt.Color(22, 92, 122));
                noOfMeals[i].setText(reslistMeals[i].getNumberOfMeal()+ " x");
                myreser.add(noOfMeals[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60+velC, 40, 50));

                restName[i].setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
                restName[i].setForeground(new java.awt.Color(49, 50, 50));
                if(mealTemp.getResID() == 1){
                restName[i].setText("Restaraunt A");
                }else if(mealTemp.getResID() == 2){
                 restName[i].setText("Restaraunt B");
                }else{
                 restName[i].setText("Restaraunt C");
                }
                
                myreser.add(restName[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60+velC, 180, -1));
                myreser.add(cancelBtn[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(970, (40+velC), -1, 70));
                rowBack[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/reserveRowBack.png"))); // NOI18N
                myreser.add(rowBack[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(50, (30+velC), 1110, 90));
                i++;
                velC +=100;
                mealCount--;
        }
    }
/*    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt){
         JLabel btn = (JLabel) evt.getSource();
        // System.out.println(btn.getToolTipText());
         StringTokenizer idlist = new StringTokenizer(btn.getToolTipText());
         Reservation.deleteRoomReservation(customerID, Integer.parseInt(idlist.nextToken()));
         Reservation.deleteMealReservation(customerID, Integer.parseInt(idlist.nextToken()));
         updateReservation();
         
        dispose();
        new Admin(Tid,customerID).setVisible(true);
    }*/
        private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt){
         JLabel btn = (JLabel) evt.getSource();
        // System.out.println(btn.getToolTipText());
      StringTokenizer idlist = new StringTokenizer(btn.getToolTipText());
         String typeOfCancel = idlist.nextToken();
         int roomID,mealID;
         //System.out.println(typeOfCancel);
         if(typeOfCancel .equals("R")){
             roomID =Integer.parseInt(idlist.nextToken());
             System.out.println(roomID);
             ReservationRooms.deleteRoomReservation(Tid, roomID);
             System.out.println("room :  ");
         }else{
            mealID =Integer.parseInt(idlist.nextToken());
             System.out.println(mealID);
             ReservationMeal.deleteMealReservation(Tid, mealID);
         }
         refreshReservations();
         //updateReservation();  
  }
   private void refreshReservations(){
        dispose();
         new Admin(Cemail,Tid).setVisible(true);
    }
    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dispose();
        new OPTA().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void viewReservationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewReservationsMouseClicked
        this.CID = idInput.getText();
        //updateReservation();
        dispose();
        new Admin(Cemail,CID).setVisible(true);
    }//GEN-LAST:event_viewReservationsMouseClicked

    private void generateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateMouseClicked
        PrintWriter out = null;
       DBConnect db= new DBConnect();
       Date s=new Date();
       
        try {
            Results x[]=db.AvailableRooms();
            Results j[]=db.MealSold();
            out=new PrintWriter(new FileWriter("Report.txt",true));
            
            out.println("------------------------------------");
            out.println("Date of Report "+ s.toString());
            out.println("Number of Customers: "+db.NoOfCustomers());
            out.println("Number of Customer that have a reservation: "+db.ReservedCustomers());
            out.println("Rooms Available : ");
            for(int i=0;i<x.length;i++)
                {out.println("Type of Room: "+x[i].getType()+" NO. of available: "+x[i].getNumberofsales()+" HotelID: "+x[i].getMealID());}
            out.println("Meals sold");
            for(int i=0;i<j.length;i++)
                {out.println("MealID: "+j[i].getMealID()+" Sold meals:"+j[i].getNumberofsales());}
            out.println("Average Room Price: "+db.AvrRoomPrice());
            out.println("Average Meal Price: "+db.AvrMealPrice());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        out.close();
        
        doneG.setVisible(true);
        
    }//GEN-LAST:event_generateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backInput;
    private javax.swing.JLabel backSide;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel doneG;
    private javax.swing.JLabel errNo;
    private javax.swing.JLabel generate;
    private javax.swing.JLabel iconUser;
    private javax.swing.JTextField idInput;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel mainTitle1;
    private javax.swing.JLabel min;
    private javax.swing.JLabel min1;
    private javax.swing.JPanel myreser;
    private javax.swing.JLabel nav;
    private javax.swing.JLabel nav1;
    private javax.swing.JLabel subNav;
    private javax.swing.JLabel subNav1;
    private javax.swing.JLabel user;
    private javax.swing.JLabel viewReservations;
    // End of variables declaration//GEN-END:variables
}
