/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafiles;

import java.util.StringTokenizer;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author aoosm
 */
public class Main extends javax.swing.JFrame {

    public String Tid;
    public String Cemail;

    /**
     * Creates new form Main
     */
    public Main() {
        this("11112222333344","ahmed@othman.io");
    }

    public Main(String id,String email) {
        initComponents();
        this.Tid = id;
        this.Cemail=email;

        errNo.setVisible(false);  
        mainHover.setVisible(true);
        roomsHover.setVisible(false);
        restaurantsHover.setVisible(false);
        myreservationHover.setVisible(false);
        Account userP = new Account();
        userP.getAccInfo(Cemail);
        
        user.setText(userP.getFname());
        nAvailA.setVisible(false);
        nAvailB.setVisible(false);
        nAvailC.setVisible(false);
        errNot.setVisible(false);
    }
    public Main(String id, boolean update,String email){
        this(id,email);
        jTabbedPane1.setSelectedIndex(3);
        mainHover.setVisible(false);
        roomsHover.setVisible(false);
        restaurantsHover.setVisible(false);
        myreservationHover.setVisible(true);
        updateReservation();
    }
        public Main(String id, String update,String email){
        this(id,email);
        jTabbedPane1.setSelectedIndex(2);
        mainHover.setVisible(false);
        roomsHover.setVisible(false);
        restaurantsHover.setVisible(true);
        myreservationHover.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconUser = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        mainTitle = new javax.swing.JLabel();
        subNav = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        nav = new javax.swing.JLabel();
        subNav1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        restIc = new javax.swing.JLabel();
        eFP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainicon = new javax.swing.JLabel();
        mrese = new javax.swing.JLabel();
        rest = new javax.swing.JLabel();
        rooms = new javax.swing.JLabel();
        main = new javax.swing.JLabel();
        mainHover = new javax.swing.JLabel();
        roomsHover = new javax.swing.JLabel();
        myreservationHover = new javax.swing.JLabel();
        restaurantsHover = new javax.swing.JLabel();
        backSide = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        mainP = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RoomsP = new javax.swing.JPanel();
        price = new javax.swing.JLabel();
        nAvailA = new javax.swing.JLabel();
        nAvailB = new javax.swing.JLabel();
        nAvailC = new javax.swing.JLabel();
        starf4 = new javax.swing.JLabel();
        starf3 = new javax.swing.JLabel();
        starf2 = new javax.swing.JLabel();
        starf1 = new javax.swing.JLabel();
        starf = new javax.swing.JLabel();
        reserveA = new javax.swing.JLabel();
        descC = new javax.swing.JLabel();
        nameA = new javax.swing.JLabel();
        descA = new javax.swing.JLabel();
        actA = new javax.swing.JLabel();
        backA = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        ReserveB = new javax.swing.JLabel();
        descCB = new javax.swing.JLabel();
        descB = new javax.swing.JLabel();
        actB = new javax.swing.JLabel();
        nameB = new javax.swing.JLabel();
        starf20 = new javax.swing.JLabel();
        starf21 = new javax.swing.JLabel();
        starf22 = new javax.swing.JLabel();
        starf23 = new javax.swing.JLabel();
        starf24 = new javax.swing.JLabel();
        priceb = new javax.swing.JLabel();
        backB = new javax.swing.JLabel();
        reserveC = new javax.swing.JLabel();
        descCCC = new javax.swing.JLabel();
        descCC = new javax.swing.JLabel();
        actC = new javax.swing.JLabel();
        nameC = new javax.swing.JLabel();
        starf25 = new javax.swing.JLabel();
        starf26 = new javax.swing.JLabel();
        starf27 = new javax.swing.JLabel();
        starf28 = new javax.swing.JLabel();
        starf29 = new javax.swing.JLabel();
        pricec = new javax.swing.JLabel();
        backC = new javax.swing.JLabel();
        errNot = new javax.swing.JLabel();
        restarauntsP = new javax.swing.JPanel();
        starf15 = new javax.swing.JLabel();
        starf16 = new javax.swing.JLabel();
        starf17 = new javax.swing.JLabel();
        starf18 = new javax.swing.JLabel();
        starf19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        starf30 = new javax.swing.JLabel();
        starf31 = new javax.swing.JLabel();
        starf32 = new javax.swing.JLabel();
        starf33 = new javax.swing.JLabel();
        starf34 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        starf35 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        starf36 = new javax.swing.JLabel();
        starf37 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        starf38 = new javax.swing.JLabel();
        starf39 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        myreser = new javax.swing.JPanel();
        errNo = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mainTitle1 = new javax.swing.JLabel();
        min1 = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        nav1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1545, 770));
        setSize(new java.awt.Dimension(1545, 770));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_male_user_50px.png"))); // NOI18N
        jPanel1.add(iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 50, -1, 60));

        user.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("User");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 70, -1, 30));

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Log Out.png"))); // NOI18N
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 60, -1, -1));

        mainTitle.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle.setText("Main Page");
        jPanel1.add(mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        subNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/sub-nav.png"))); // NOI18N
        jPanel1.add(subNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1560, -1));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/min.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 20, 20, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_Close_30px_1.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 10, -1, 20));

        nav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/nav.png"))); // NOI18N
        nav.setToolTipText("");
        jPanel1.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, -1));

        subNav1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/sub-nav.png"))); // NOI18N
        jPanel1.add(subNav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1560, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_shopping_cart_30px.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        restIc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_reservation_24px.png"))); // NOI18N
        jPanel2.add(restIc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        eFP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Exit From Program.png"))); // NOI18N
        eFP.setToolTipText("");
        eFP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eFPMouseClicked(evt);
            }
        });
        jPanel2.add(eFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 240, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_bedroom_interior_50px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 40, 40));

        mainicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_home_50px.png"))); // NOI18N
        jPanel2.add(mainicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 30, 40));

        mrese.setBackground(new java.awt.Color(255, 255, 255));
        mrese.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        mrese.setForeground(new java.awt.Color(255, 255, 255));
        mrese.setText("My reservations");
        mrese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mrese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mreseMouseClicked(evt);
            }
        });
        jPanel2.add(mrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 210, -1));

        rest.setBackground(new java.awt.Color(255, 255, 255));
        rest.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        rest.setForeground(new java.awt.Color(255, 255, 255));
        rest.setText("Resturants");
        rest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restMouseClicked(evt);
            }
        });
        jPanel2.add(rest, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 210, -1));

        rooms.setBackground(new java.awt.Color(255, 255, 255));
        rooms.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        rooms.setForeground(new java.awt.Color(255, 255, 255));
        rooms.setText("Rooms");
        rooms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsMouseClicked(evt);
            }
        });
        jPanel2.add(rooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 210, -1));

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        main.setForeground(new java.awt.Color(255, 255, 255));
        main.setText("Main");
        main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainMouseClicked(evt);
            }
        });
        jPanel2.add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 200, -1));

        mainHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/libackground.png"))); // NOI18N
        jPanel2.add(mainHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 310, 80));

        roomsHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/libackground.png"))); // NOI18N
        jPanel2.add(roomsHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 310, 80));

        myreservationHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/libackground.png"))); // NOI18N
        jPanel2.add(myreservationHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 310, 80));

        restaurantsHover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/libackground.png"))); // NOI18N
        jPanel2.add(restaurantsHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 310, 100));

        backSide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/side-back.png"))); // NOI18N
        jPanel2.add(backSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 670));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 380, -1));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));

        mainP.setBackground(new java.awt.Color(153, 0, 51));
        mainP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/feedback.png"))); // NOI18N
        jLabel12.setToolTipText("");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mainP.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 600, 170, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_Location_24px.png"))); // NOI18N
        mainP.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 320, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/We offer you the best services ,  Rooms , Resturants, Parking, .png"))); // NOI18N
        jLabel10.setToolTipText("");
        mainP.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 320, 100));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/sepr.png"))); // NOI18N
        jLabel9.setToolTipText("");
        mainP.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 630, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/The best place to.png"))); // NOI18N
        jLabel4.setToolTipText("");
        mainP.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 540, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/rest like home.png"))); // NOI18N
        mainP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 580, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/beautiful-luxury-outdoor-swimming-pool-hotel-resort.png"))); // NOI18N
        jLabel5.setToolTipText("");
        mainP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, -1));

        jTabbedPane1.addTab("tab2", mainP);

        RoomsP.setBackground(new java.awt.Color(255, 255, 255));
        RoomsP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        price.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        price.setForeground(new java.awt.Color(51, 51, 51));
        price.setText("Price : 200$");
        price.setToolTipText("");
        RoomsP.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, -1, 40));

        nAvailA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Not Available.png"))); // NOI18N
        nAvailA.setToolTipText("");
        RoomsP.add(nAvailA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        nAvailB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Not Available.png"))); // NOI18N
        nAvailB.setToolTipText("");
        RoomsP.add(nAvailB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        nAvailC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Not Available.png"))); // NOI18N
        nAvailC.setToolTipText("");
        RoomsP.add(nAvailC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        starf4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        starf3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        starf2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        starf1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        starf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        reserveA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Reserve.png"))); // NOI18N
        reserveA.setToolTipText("");
        reserveA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reserveA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reserveAMouseClicked(evt);
            }
        });
        RoomsP.add(reserveA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 170, 40));

        descC.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        descC.setForeground(new java.awt.Color(51, 51, 51));
        descC.setText("A luxurious 2 bed room with an  amazing view");
        RoomsP.add(descC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 280, 30));

        nameA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Class A.png"))); // NOI18N
        RoomsP.add(nameA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 60, 40));

        descA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Description _.png"))); // NOI18N
        RoomsP.add(descA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        actA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Available.png"))); // NOI18N
        RoomsP.add(actA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        backA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/interior-modern-comfortable-hotel-room.png"))); // NOI18N
        RoomsP.add(backA, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 180, 310, 350));

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/ROOMS.png"))); // NOI18N
        title.setToolTipText("");
        RoomsP.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 199, 44));

        ReserveB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Reserve.png"))); // NOI18N
        ReserveB.setToolTipText("");
        ReserveB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReserveB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReserveBMouseClicked(evt);
            }
        });
        RoomsP.add(ReserveB, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 170, 40));

        descCB.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        descCB.setForeground(new java.awt.Color(51, 51, 51));
        descCB.setText("A luxurious 2 bed room with an  amazing view");
        RoomsP.add(descCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 280, 30));

        descB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Description _.png"))); // NOI18N
        RoomsP.add(descB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        actB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Available.png"))); // NOI18N
        RoomsP.add(actB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        nameB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Class B.png"))); // NOI18N
        RoomsP.add(nameB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 60, 40));

        starf20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        starf21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, -1));

        starf22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        starf23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf23, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, -1, -1));

        starf24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf24, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, -1));

        priceb.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        priceb.setForeground(new java.awt.Color(51, 51, 51));
        priceb.setText("Price : 150$");
        priceb.setToolTipText("");
        RoomsP.add(priceb, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, 40));

        backB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/luxury-bedroom-suite-resort-high-rise-hotel-with-working-table.png"))); // NOI18N
        RoomsP.add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 310, 350));

        reserveC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Reserve.png"))); // NOI18N
        reserveC.setToolTipText("");
        reserveC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reserveC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reserveCMouseClicked(evt);
            }
        });
        RoomsP.add(reserveC, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 170, 40));

        descCCC.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        descCCC.setForeground(new java.awt.Color(51, 51, 51));
        descCCC.setText("A luxurious 2 bed room with an  amazing view");
        RoomsP.add(descCCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, 280, 30));

        descCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Description _.png"))); // NOI18N
        RoomsP.add(descCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, -1, -1));

        actC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Available.png"))); // NOI18N
        RoomsP.add(actC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        nameC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Class C.png"))); // NOI18N
        RoomsP.add(nameC, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 60, 40));

        starf25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 350, -1, -1));

        starf26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, -1, -1));

        starf27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 350, -1, -1));

        starf28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 350, -1, -1));

        starf29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        RoomsP.add(starf29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 350, -1, -1));

        pricec.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        pricec.setForeground(new java.awt.Color(51, 51, 51));
        pricec.setText("Price : 200$");
        pricec.setToolTipText("");
        RoomsP.add(pricec, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, -1, 40));

        backC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/modern-studio-apartment-design-with-bedroom-living-space.png"))); // NOI18N
        RoomsP.add(backC, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 310, 350));

        errNot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/errNot.png"))); // NOI18N
        RoomsP.add(errNot, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 300, 40));

        jTabbedPane1.addTab("tab4", RoomsP);

        restarauntsP.setBackground(new java.awt.Color(255, 255, 255));
        restarauntsP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        starf15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, -1, -1));

        starf16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        starf17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        starf18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        starf19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Restaurants.png"))); // NOI18N
        restarauntsP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 209, 69));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/View Meals.png"))); // NOI18N
        jLabel37.setToolTipText("");
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.setFocusTraversalPolicyProvider(true);
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        restarauntsP.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 180, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Available.png"))); // NOI18N
        jLabel38.setToolTipText("");
        restarauntsP.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 80, 20));

        jLabel34.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Italian");
        restarauntsP.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 120, 30));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/tamara-malaniy-gdiNvl_hvso-unsplash.png"))); // NOI18N
        restarauntsP.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 191, 331, 310));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/View Meals.png"))); // NOI18N
        jLabel40.setToolTipText("");
        jLabel40.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel40.setFocusTraversalPolicyProvider(true);
        jLabel40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel40MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel40MouseEntered(evt);
            }
        });
        restarauntsP.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 180, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Available.png"))); // NOI18N
        jLabel41.setToolTipText("");
        restarauntsP.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 80, 20));

        jLabel42.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 51, 51));
        jLabel42.setText("Mexican");
        jLabel42.setToolTipText("");
        restarauntsP.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 120, 30));

        starf30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf30, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, -1));

        starf31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf31, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        starf32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf32, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, -1));

        starf33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf33, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, -1, -1));

        starf34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf34, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/dmitriy-k-4zTf1NVuw-0-unsplash.png"))); // NOI18N
        restarauntsP.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 331, 310));

        starf35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, -1, -1));

        jLabel43.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(51, 51, 51));
        jLabel43.setText("Egyptian");
        jLabel43.setToolTipText("");
        restarauntsP.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 120, 30));

        starf36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, -1, -1));

        starf37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf37, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 380, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Available.png"))); // NOI18N
        jLabel44.setToolTipText("");
        restarauntsP.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 80, 20));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/View Meals.png"))); // NOI18N
        jLabel45.setToolTipText("");
        jLabel45.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel45.setFocusTraversalPolicyProvider(true);
        jLabel45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel45MouseClicked(evt);
            }
        });
        restarauntsP.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 180, -1));

        starf38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf38, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, -1, -1));

        starf39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_star_48px.png"))); // NOI18N
        restarauntsP.add(starf39, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 380, -1, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/aleksandr-bushmakin-tNqC8a6qW1Y-unsplash.png"))); // NOI18N
        restarauntsP.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, 331, 310));

        jTabbedPane1.addTab("tab1", restarauntsP);

        myreser.setBackground(new java.awt.Color(255, 255, 255));
        myreser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        errNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/errN.png"))); // NOI18N
        myreser.add(errNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 520, 50));

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Refresh.png"))); // NOI18N
        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.setDoubleBuffered(true);
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        myreser.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 597, -1, 60));

        jTabbedPane1.addTab("tab3", myreser);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 1180, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTitle1.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        mainTitle1.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle1.setText("Main Page");
        jPanel3.add(mainTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 30));

        min1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/min.png"))); // NOI18N
        min1.setToolTipText("");
        min1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                min1MouseClicked(evt);
            }
        });
        jPanel3.add(min1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 20, 20, -1));

        close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_Close_30px_1.png"))); // NOI18N
        close1.setToolTipText("");
        close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });
        jPanel3.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 10, -1, 20));

        nav1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/nav.png"))); // NOI18N
        nav1.setToolTipText("");
        jPanel3.add(nav1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void min1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_min1MouseClicked

    }//GEN-LAST:event_min1MouseClicked

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked

    }//GEN-LAST:event_close1MouseClicked

    private void mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainMouseClicked

        jTabbedPane1.setSelectedIndex(0);
        mainHover.setVisible(true);
        roomsHover.setVisible(false);
        restaurantsHover.setVisible(false);
        myreservationHover.setVisible(false);
    }//GEN-LAST:event_mainMouseClicked

    private void roomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMouseClicked

        Rooms[] roomList = new Rooms[3];
        jTabbedPane1.setSelectedIndex(1);
        mainHover.setVisible(false);
        roomsHover.setVisible(true);
        restaurantsHover.setVisible(false);
        myreservationHover.setVisible(false);
        roomList = Rooms.viewRooms(1);
        price.setText("Price: " + Double.toString(roomList[0].getPrice()) + "$");
        priceb.setText("Price: " + Double.toString(roomList[1].getPrice()) + "$");
        pricec.setText("Price: " + Double.toString(roomList[2].getPrice()) + "$");
        if (roomList[0].isAvailable()) {
            actA.setVisible(true);
            nAvailA.setVisible(false);
        } else {
            actA.setVisible(false);
            nAvailA.setVisible(true);
        }
        if (roomList[1].isAvailable()) {
            actB.setVisible(true);
            nAvailB.setVisible(false);
        } else {
            actB.setVisible(false);
            nAvailB.setVisible(true);
        }
         if (roomList[2].isAvailable()) {
            actC.setVisible(true);
            nAvailC.setVisible(false);
        } else {
            actC.setVisible(false);
            nAvailC.setVisible(true);
        }
    }//GEN-LAST:event_roomsMouseClicked

    private void restMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restMouseClicked

        jTabbedPane1.setSelectedIndex(2);
        mainHover.setVisible(false);
        roomsHover.setVisible(false);
        restaurantsHover.setVisible(true);
        myreservationHover.setVisible(false);
    }//GEN-LAST:event_restMouseClicked

    private void mreseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mreseMouseClicked
        jTabbedPane1.setSelectedIndex(3);
        mainHover.setVisible(false);
        roomsHover.setVisible(false);
        restaurantsHover.setVisible(false);
        myreservationHover.setVisible(true);
        updateReservation();
        refreshReservations();
    }//GEN-LAST:event_mreseMouseClicked
    

    private void updateReservation(){
      /////////////////////////////////////////
        int vel = 0;
        int velC= 0;
        int noRows =0;
        int noRooms=0;
        int noMeals=0;
        /////////////////////////////////////////
        ReservationRooms[] reslistRooms = ReservationRooms.viewReservations(Cemail);
         ReservationMeal[] reslistMeals = ReservationMeal.viewReservations(Cemail);
        //////////////////////////////////////////
        //common 
      
        noRooms = reslistRooms.length;
        //System.out.println(noRooms);
        noMeals = reslistMeals.length;
         noRows = noRooms+noMeals;
        JLabel[] rowBack = new JLabel[noRows];
        JLabel[] cancelBtn = new JLabel[noRows];
        Meal mealTemp = new Meal();
        int mealCount = noMeals;
        int roomCount = noRooms;
           if((reslistMeals.length+reslistRooms.length ) == 0){
            errNo.setVisible(true);
        }else{
          errNo.setVisible(false);
           }
        //room component 
        JLabel[] RoomName = new JLabel[roomCount];
        JLabel[] startDate = new JLabel[roomCount];
        JLabel[] endDate = new JLabel[roomCount];
        JLabel[] priceRoom = new JLabel[roomCount];
        //meals component
        JLabel[] restName = new JLabel[mealCount];
        JLabel[] noOfMeals = new JLabel[mealCount];
        JLabel[] mealName = new JLabel[mealCount];
        JLabel[] priceMeal = new JLabel[mealCount];
     
        int k =0;
        while(roomCount>0){
           RoomName[k] = new JLabel();
           startDate[k] = new JLabel();
           endDate[k] = new JLabel();
           priceRoom[k] = new JLabel();
           rowBack[k] =new JLabel();
           cancelBtn[k] = new JLabel();
        
           cancelBtn[k].setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Cancel.png"))); // NOI18N
           cancelBtn[k].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
           cancelBtn[k].setToolTipText("R" +" "+ reslistRooms[k].getRoomID());
           cancelBtn[k].addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    cancelBtnMouseClicked(evt);
                }
            });
 	
           priceRoom[k].setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
           priceRoom[k].setForeground(new java.awt.Color(49, 50, 50));
           priceRoom[k].setText("Price: " + Double.toString(reslistRooms[k].getTotalPrice()));
           myreser.add(priceRoom[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40+velC, 180, 70));   

           endDate[k].setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
           endDate[k].setForeground(new java.awt.Color(22, 92, 122));
           endDate[k].setText("End Date: " + reslistRooms[k].getEndDate());
           myreser.add(endDate[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 63+velC, 230, -1)); 

           startDate[k].setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
           startDate[k].setForeground(new java.awt.Color(22, 92, 122));
           startDate[k].setText("Start Date: " + reslistRooms[k].getArrivalDate());
           myreser.add(startDate[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 55+velC, 230, 50));

           RoomName[k].setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
           RoomName[k].setForeground(new java.awt.Color(49, 50, 50));
           if(reslistRooms[k].getRoomID() == 1){
               RoomName[k].setText(reslistRooms[k].getNumberOfRooms() + "x Room A");
           }else if(reslistRooms[k].getRoomID() == 2){
               RoomName[k].setText(reslistRooms[k].getNumberOfRooms() + "x Room B");
           }else{
               RoomName[k].setText(reslistRooms[k].getNumberOfRooms() + "x Room C");
           }
           
            myreser.add(RoomName[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60+velC, 160, -1));
            myreser.add(cancelBtn[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40+velC, -1, 70));
            rowBack[k].setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/reserveRowBack.png"))); // NOI18N
            myreser.add(rowBack[k], new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30+velC, 1110, 90));
            roomCount--;
            k++;
            velC+=100;
        }
      
       // velC -=100;
        int i =0;
        while(mealCount>0 ){
                restName[i] = new JLabel();
                noOfMeals[i] = new JLabel();
                mealName[i] = new JLabel();
                priceMeal[i] = new JLabel();
                rowBack[i] =new JLabel();
                cancelBtn[i] = new JLabel();
        
                cancelBtn[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Cancel.png"))); // NOI18N
                cancelBtn[i].setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                cancelBtn[i].setToolTipText("M"+" "+ reslistMeals[i].getMealID());
                cancelBtn[i].addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        cancelBtnMouseClicked(evt);
                    }
                });
                
                priceMeal[i].setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                priceMeal[i].setForeground(new java.awt.Color(49, 50, 50));
                priceMeal[i].setText("Price: " + Double.toString(reslistMeals[i].getTotalPrice()));
                myreser.add(priceMeal[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40+velC, 180, 70));

                mealName[i].setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
                mealName[i].setForeground(new java.awt.Color(49, 50, 50));
                mealTemp.fillMealInfo(reslistMeals[i].getMealID());
                mealName[i].setText(mealTemp.getName());
                myreser.add(mealName[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60+velC, 160, 50));

                noOfMeals[i].setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
                noOfMeals[i].setForeground(new java.awt.Color(22, 92, 122));
                noOfMeals[i].setText(reslistMeals[i].getNumberOfMeal()+ " x");
                myreser.add(noOfMeals[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60+velC, 40, 50));

                restName[i].setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
                restName[i].setForeground(new java.awt.Color(49, 50, 50));
                if(mealTemp.getResID() == 1){
                restName[i].setText("Italian");
                }else if(mealTemp.getResID() == 2){
                 restName[i].setText("Mexican");
                }else{
                 restName[i].setText("Egyptian");
                }
                
                myreser.add(restName[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60+velC, 180, -1));
                myreser.add(cancelBtn[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(970, (40+velC), -1, 70));
                rowBack[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/reserveRowBack.png"))); // NOI18N
                myreser.add(rowBack[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(50, (30+velC), 1110, 90));
                i++;
                velC +=100;
                mealCount--;
        }
    }
    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt){
         JLabel btn = (JLabel) evt.getSource();
        // System.out.println(btn.getToolTipText());
         StringTokenizer idlist = new StringTokenizer(btn.getToolTipText());
         String typeOfCancel = idlist.nextToken();
         int roomID,mealID;
        // System.out.println(typeOfCancel);
         if(typeOfCancel .equals("R")){
             roomID =Integer.parseInt(idlist.nextToken());
             System.out.println(roomID);
             ReservationRooms.deleteRoomReservation(Cemail, roomID);
             System.out.println("room :  ");
         }else{
            mealID =Integer.parseInt(idlist.nextToken());
             System.out.println(mealID);
             ReservationMeal.deleteMealReservation(Cemail, mealID);
         }
         refreshReservations();
         updateReservation();
  }
  
    private void eFPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eFPMouseClicked
        dispose();
    }//GEN-LAST:event_eFPMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        dispose();
        new OPTA().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void reserveAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveAMouseClicked
        if(nAvailA.isVisible()){
            //error
            errNot.setVisible(true);
            return;
        }
            
        popUpReserve pop = new popUpReserve(Tid,Cemail,1);
        pop.setVisible(true);

    }//GEN-LAST:event_reserveAMouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        if(nAvailC.isVisible()){
           errNot.setVisible(true);
            return;
        }
        
        popUpReserveMeals p = new popUpReserveMeals(1, Tid,Cemail);
        p.setVisible(true);
    }//GEN-LAST:event_jLabel37MouseClicked

    private void ReserveBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReserveBMouseClicked
        
        if(nAvailB.isVisible()){
            errNot.setVisible(true);
            return;
        }
        popUpReserve pop = new popUpReserve(Tid,Cemail,2);

        pop.setVisible(true);
    }//GEN-LAST:event_ReserveBMouseClicked

    private void reserveCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reserveCMouseClicked
           popUpReserve pop = new popUpReserve(Tid,Cemail,3);
           pop.setVisible(true);
    }//GEN-LAST:event_reserveCMouseClicked

    private void jLabel40MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel40MouseEntered

    private void jLabel40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel40MouseClicked
        popUpReserveMeals p = new popUpReserveMeals(2, Tid,Cemail);
        p.setVisible(true);
    }//GEN-LAST:event_jLabel40MouseClicked

    private void jLabel45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel45MouseClicked
        popUpReserveMeals p = new popUpReserveMeals(3, Tid,Cemail);
        p.setVisible(true);
    }//GEN-LAST:event_jLabel45MouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
      refreshReservations();
    }//GEN-LAST:event_refreshMouseClicked
    private void refreshReservations(){
        dispose();
        new Main(Tid,true,Cemail).setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ReserveB;
    private javax.swing.JPanel RoomsP;
    private javax.swing.JLabel actA;
    private javax.swing.JLabel actB;
    private javax.swing.JLabel actC;
    private javax.swing.JLabel backA;
    private javax.swing.JLabel backB;
    private javax.swing.JLabel backC;
    private javax.swing.JLabel backSide;
    private javax.swing.JLabel close;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel descA;
    private javax.swing.JLabel descB;
    private javax.swing.JLabel descC;
    private javax.swing.JLabel descCB;
    private javax.swing.JLabel descCC;
    private javax.swing.JLabel descCCC;
    private javax.swing.JLabel eFP;
    private javax.swing.JLabel errNo;
    private javax.swing.JLabel errNot;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel main;
    private javax.swing.JLabel mainHover;
    private javax.swing.JPanel mainP;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel mainTitle1;
    private javax.swing.JLabel mainicon;
    private javax.swing.JLabel min;
    private javax.swing.JLabel min1;
    private javax.swing.JLabel mrese;
    private javax.swing.JPanel myreser;
    private javax.swing.JLabel myreservationHover;
    private javax.swing.JLabel nAvailA;
    private javax.swing.JLabel nAvailB;
    private javax.swing.JLabel nAvailC;
    private javax.swing.JLabel nameA;
    private javax.swing.JLabel nameB;
    private javax.swing.JLabel nameC;
    private javax.swing.JLabel nav;
    private javax.swing.JLabel nav1;
    private javax.swing.JLabel price;
    private javax.swing.JLabel priceb;
    private javax.swing.JLabel pricec;
    private javax.swing.JLabel refresh;
    private javax.swing.JLabel reserveA;
    private javax.swing.JLabel reserveC;
    private javax.swing.JLabel rest;
    private javax.swing.JLabel restIc;
    private javax.swing.JPanel restarauntsP;
    private javax.swing.JLabel restaurantsHover;
    private javax.swing.JLabel rooms;
    private javax.swing.JLabel roomsHover;
    private javax.swing.JLabel starf;
    private javax.swing.JLabel starf1;
    private javax.swing.JLabel starf15;
    private javax.swing.JLabel starf16;
    private javax.swing.JLabel starf17;
    private javax.swing.JLabel starf18;
    private javax.swing.JLabel starf19;
    private javax.swing.JLabel starf2;
    private javax.swing.JLabel starf20;
    private javax.swing.JLabel starf21;
    private javax.swing.JLabel starf22;
    private javax.swing.JLabel starf23;
    private javax.swing.JLabel starf24;
    private javax.swing.JLabel starf25;
    private javax.swing.JLabel starf26;
    private javax.swing.JLabel starf27;
    private javax.swing.JLabel starf28;
    private javax.swing.JLabel starf29;
    private javax.swing.JLabel starf3;
    private javax.swing.JLabel starf30;
    private javax.swing.JLabel starf31;
    private javax.swing.JLabel starf32;
    private javax.swing.JLabel starf33;
    private javax.swing.JLabel starf34;
    private javax.swing.JLabel starf35;
    private javax.swing.JLabel starf36;
    private javax.swing.JLabel starf37;
    private javax.swing.JLabel starf38;
    private javax.swing.JLabel starf39;
    private javax.swing.JLabel starf4;
    private javax.swing.JLabel subNav;
    private javax.swing.JLabel subNav1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
