/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafiles;


import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;

/**
 *
 * @author aoosm
 */

public class OPTA extends javax.swing.JFrame {

    /**
     * Creates new form OPTA
     */
    
    public OPTA() {
        initComponents();
        email.setBackground(new java.awt.Color(0,0,0,1)); 
        password.setBackground(new java.awt.Color(0,0,0,1));
        err.setVisible(false);
        //add placeholder style
        addPlaceHolderStyle(email);
        addPlaceHolderStyle(password);
    }
    
    // methods of placeholder style
    
    public void addPlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.WHITE);
    }
    
    public void removePlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.WHITE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        signBtnNav = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        forgetPassword = new javax.swing.JLabel();
        err = new javax.swing.JLabel();
        registerBtnNav = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        sep1 = new javax.swing.JLabel();
        lock = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        sep = new javax.swing.JLabel();
        customer = new javax.swing.JLabel();
        backSign = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signBtnNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Sign in.png"))); // NOI18N
        signBtnNav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(signBtnNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 100, 50));

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_help_30px.png"))); // NOI18N
        jPanel1.add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, -1, -1));

        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Login.png"))); // NOI18N
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 550, 240, 60));

        forgetPassword.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        forgetPassword.setForeground(new java.awt.Color(255, 255, 255));
        forgetPassword.setText("Forget Password?");
        jPanel1.add(forgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 140, 40));

        err.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/errMassage.png"))); // NOI18N
        err.setToolTipText("");
        jPanel1.add(err, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 260, 50));

        registerBtnNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Register.png"))); // NOI18N
        registerBtnNav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtnNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnNavMouseClicked(evt);
            }
        });
        jPanel1.add(registerBtnNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 110, 70));

        password.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        password.setBorder(null);
        password.setEchoChar('\u0000');
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordMouseEntered(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 210, 30));

        sep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Shape 1.png"))); // NOI18N
        jPanel1.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 270, 50));

        lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/lock_30px.png"))); // NOI18N
        jPanel1.add(lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 20, 50));

        email.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        email.setBorder(null);
        email.setCaretColor(new java.awt.Color(255, 255, 255));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, 210, 30));

        sep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Shape 1.png"))); // NOI18N
        jPanel1.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 270, 50));

        customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/customer_26px.png"))); // NOI18N
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 30, 40));

        backSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/background.png"))); // NOI18N
        jPanel1.add(backSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 440, 440));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/min.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 20, 20, 30));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_Close_30px_1.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 20, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/LOGO.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/background2.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1570, 790));

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
            this.setState(this.ICONIFIED);
        //min
    }//GEN-LAST:event_minMouseClicked

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed
//
    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        
        
    }//GEN-LAST:event_emailMouseEntered
 //
    private void passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseEntered
        
       
    }//GEN-LAST:event_passwordMouseEntered

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
    
    }//GEN-LAST:event_emailMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        
    }//GEN-LAST:event_passwordMouseClicked

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
       
       String name = email.getText();
       String pass = String.valueOf(password.getPassword());
       String id = null;
       boolean status = false;
      
        status = Account.login(name, pass);
        System.out.println(status);
        
       if(status){
           //main page
           err.setVisible(false);
           dispose();
           Account poi = new Account();
           poi.getAccInfo(name);
           id = poi.getAccID();
           System.out.println(id);
           if((poi.getRole()).equals("customer")){
            Main pg = new Main(id,name);
            pg.setVisible(true);
           }else{
            Admin pg = new Admin(name);
            pg.setVisible(true);
           }
           
       }else{
           err.setVisible(true);
       }
    }//GEN-LAST:event_loginBtnMouseClicked

    private void registerBtnNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnNavMouseClicked
      
        dispose();
        new OPTAregister().setVisible(true);
    }//GEN-LAST:event_registerBtnNavMouseClicked

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        if(email.getText().equals("Email"))
        {
            email.setText(null);
            email.requestFocus();
            //remove placeholder style
            removePlaceHolderStyle(email);
        }
    }//GEN-LAST:event_emailFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        if(password.getText().equals("Password"))
        {
            password.setText(null);
            password.requestFocus();
            //set password character
            password.setEchoChar('\u2022');
            //remove placeholder style
            removePlaceHolderStyle(password);
        }
    }//GEN-LAST:event_passwordFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if(email.getText().length() == 0)
        {
           //add placeholder style
           addPlaceHolderStyle(email);
           email.setText("Email");
        }
    }//GEN-LAST:event_emailFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if(password.getText().length() == 0)
        {
           //add placeholder style
           addPlaceHolderStyle(password);
           password.setText("Password");
           password.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_passwordFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OPTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OPTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OPTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OPTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OPTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backSign;
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JLabel customer;
    private javax.swing.JTextField email;
    private javax.swing.JLabel err;
    private javax.swing.JLabel forgetPassword;
    private javax.swing.JLabel help;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lock;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel min;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel registerBtnNav;
    private javax.swing.JLabel sep;
    private javax.swing.JLabel sep1;
    private javax.swing.JLabel signBtnNav;
    // End of variables declaration//GEN-END:variables
}
