/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javafiles;


import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;

/**
 *
 * @author aoosm
 */

public class OPTAregister extends javax.swing.JFrame {

    /**
     * Creates new form OPTA
     */
    public OPTAregister() {
        initComponents();
        editComponents();
    }
    private void editComponents(){
        firstName.setBackground(new java.awt.Color(0,0,0,1)); 
        lastName.setBackground(new java.awt.Color(0,0,0,1)); 
        password.setBackground(new java.awt.Color(0,0,0,1));
        email.setBackground(new java.awt.Color(0,0,0,1));
        id.setBackground(new java.awt.Color(0,0,0,1));
        address.setBackground(new java.awt.Color(0,0,0,1));
        phoneNumber.setBackground(new java.awt.Color(0,0,0,1));
        errM.setVisible(false);
        errPass.setVisible(false);
        errEmail.setVisible(false);
        errID.setVisible(false);
        addPlaceHolderStyle(firstName);
        addPlaceHolderStyle(lastName);
        addPlaceHolderStyle(email);
        addPlaceHolderStyle(password);
        addPlaceHolderStyle(id);
        addPlaceHolderStyle(address);
        addPlaceHolderStyle(phoneNumber);
    }
    
    // methods of placeholder style
    
    public void addPlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.WHITE);
    }
    
    public void removePlaceHolderStyle(JTextField textField) {
        Font font = textField.getFont();
        font = font.deriveFont(Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.WHITE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerBtnNav = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        sep4 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        sep5 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        sep2 = new javax.swing.JLabel();
        signBtnNav = new javax.swing.JLabel();
        errID = new javax.swing.JLabel();
        errEmail = new javax.swing.JLabel();
        errPass = new javax.swing.JLabel();
        errM = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        registerBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        lastName = new javax.swing.JTextField();
        sep3 = new javax.swing.JLabel();
        sep1 = new javax.swing.JLabel();
        lock = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        sep6 = new javax.swing.JLabel();
        sep = new javax.swing.JLabel();
        customer = new javax.swing.JLabel();
        backSign = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_phone_case_30px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 20, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_address_30px.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, 30));

        registerBtnNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/RegisterW.png"))); // NOI18N
        registerBtnNav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(registerBtnNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 100, 70));

        id.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("National ID");
        id.setBorder(null);
        id.setCaretColor(new java.awt.Color(255, 255, 255));
        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFocusLost(evt);
            }
        });
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                idMouseEntered(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 240, 30));

        sep4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Shape 1.png"))); // NOI18N
        jPanel1.add(sep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 270, 50));

        address.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("Address");
        address.setBorder(null);
        address.setCaretColor(new java.awt.Color(255, 255, 255));
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addressMouseEntered(evt);
            }
        });
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 240, 20));

        sep5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Shape 1.png"))); // NOI18N
        jPanel1.add(sep5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 270, 50));

        email.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("Email");
        email.setBorder(null);
        email.setCaretColor(new java.awt.Color(255, 255, 255));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailMouseEntered(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 240, 30));

        sep2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Shape 2.png"))); // NOI18N
        jPanel1.add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 110, 50));

        signBtnNav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Sign inB.png"))); // NOI18N
        signBtnNav.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signBtnNav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signBtnNavMouseClicked(evt);
            }
        });
        jPanel1.add(signBtnNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 100, 50));

        errID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/National ID must be 14 Number.png"))); // NOI18N
        jPanel1.add(errID, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 280, 40));

        errEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/This Email Used Before.png"))); // NOI18N
        jPanel1.add(errEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 230, 40));

        errPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/6 Digit , UpperCase Letter, LowerCase Letter.png"))); // NOI18N
        jPanel1.add(errPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 370, 40));

        errM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/err.png"))); // NOI18N
        jPanel1.add(errM, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 190, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_orcid_32px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 30, 30));

        registerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/registerBtn.png"))); // NOI18N
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 220, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_envelope_32px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 340, 30, 30));

        password.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        password.setBorder(null);
        password.setEchoChar('\u0000');
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passwordMouseEntered(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 210, 30));

        lastName.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        lastName.setForeground(new java.awt.Color(255, 255, 255));
        lastName.setText("Last Name");
        lastName.setBorder(null);
        lastName.setCaretColor(new java.awt.Color(255, 255, 255));
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastNameFocusLost(evt);
            }
        });
        lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lastNameMouseEntered(evt);
            }
        });
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        jPanel1.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, -1, 30));

        sep3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Shape 2.png"))); // NOI18N
        jPanel1.add(sep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, 110, 50));

        sep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Shape 1.png"))); // NOI18N
        jPanel1.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 270, 50));

        lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/lock_30px.png"))); // NOI18N
        jPanel1.add(lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 20, 50));

        firstName.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        firstName.setForeground(new java.awt.Color(255, 255, 255));
        firstName.setText("First Name");
        firstName.setBorder(null);
        firstName.setCaretColor(new java.awt.Color(255, 255, 255));
        firstName.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstNameFocusLost(evt);
            }
        });
        firstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstNameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                firstNameMouseEntered(evt);
            }
        });
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        jPanel1.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, -1, 30));

        phoneNumber.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        phoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumber.setText("Phone Number");
        phoneNumber.setBorder(null);
        phoneNumber.setCaretColor(new java.awt.Color(255, 255, 255));
        phoneNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneNumberFocusLost(evt);
            }
        });
        phoneNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneNumberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                phoneNumberMouseEntered(evt);
            }
        });
        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberActionPerformed(evt);
            }
        });
        jPanel1.add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 240, 30));

        sep6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Shape 1.png"))); // NOI18N
        jPanel1.add(sep6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 270, 50));

        sep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/Shape 1.png"))); // NOI18N
        jPanel1.add(sep, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 270, 50));

        customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/customer_26px.png"))); // NOI18N
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, 30, 40));

        backSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/backgroundR.png"))); // NOI18N
        jPanel1.add(backSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 380, 520));

        min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/min.png"))); // NOI18N
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });
        jPanel1.add(min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 20, 20, 30));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/icons8_Close_30px_1.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 20, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/LOGO.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaimgs/background2.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1570, 790));

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
            this.setState(this.ICONIFIED);
        //min
    }//GEN-LAST:event_minMouseClicked

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed
//
    private void firstNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstNameMouseEntered
        
        
    }//GEN-LAST:event_firstNameMouseEntered
 //
    private void passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseEntered
        
       
    }//GEN-LAST:event_passwordMouseEntered

    private void firstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstNameMouseClicked
        
        
    }//GEN-LAST:event_firstNameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
       // password.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        String fname,Id, lname, addressR, passwordR, phoneR, emailR;
        boolean state = false;
        Customer person = null; 
     
        Verifier ver = new Verifier();

        fname =  firstName.getText();
        lname = lastName.getText();
        Id = id.getText();
        addressR = address.getText();
        passwordR = String.valueOf(password.getPassword());
        phoneR = phoneNumber.getText();
        emailR = email.getText();
        
        // if no empty fields and email is valid email address execute the query 
        //needs to add password verifer (done) and a more logical display message to user if password or email isnot valid
        
      
        if( fname != null  && lname != null && Id != null && addressR != null && passwordR != null && phoneR != null && emailR != null&& ver.emailVerify(emailR) && ver.passwordVerify(passwordR) && ver.idVerify(Id))
        { person =new Customer(fname, lname,'M',addressR, phoneR,Id, emailR, passwordR);
           state = person.addCustomer();
        }
        
        
        if(state){
            // go to login
                 dispose();
                 new OPTA().setVisible(true);
        }else{
            if(!ver.emailVerify(emailR)){
                errEmail.setVisible(true);
                errPass.setVisible(false);
                errM.setVisible(false);
                errID.setVisible(false);
            }else if(!ver.passwordVerify(passwordR)){
                errEmail.setVisible(false);
                errPass.setVisible(true);
                errM.setVisible(false);
                errID.setVisible(false);
            }else if(!ver.idVerify(Id)){
                errEmail.setVisible(false);
                errPass.setVisible(false);
                errM.setVisible(false);
                errID.setVisible(true);
            }else{
                errM.setVisible(true);
                errEmail.setVisible(false);
                errPass.setVisible(false);
                errID.setVisible(false);
            }
        }
    }//GEN-LAST:event_registerBtnMouseClicked
    
    private void lastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameMouseClicked

    private void lastNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastNameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameMouseEntered

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseClicked

    private void emailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMouseEntered

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idMouseClicked

    private void idMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_idMouseEntered

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addressMouseClicked

    private void addressMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addressMouseEntered

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void phoneNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneNumberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberMouseClicked

    private void phoneNumberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneNumberMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberMouseEntered

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    private void signBtnNavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signBtnNavMouseClicked
    
        dispose();
        new OPTA().setVisible(true);
        
    }//GEN-LAST:event_signBtnNavMouseClicked

    private void firstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusGained
        if(firstName.getText().equals("First Name"))
        {
            firstName.setText(null);
            firstName.requestFocus();
            //remove placeholder style
            removePlaceHolderStyle(firstName);
        }
    }//GEN-LAST:event_firstNameFocusGained

    private void lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusGained
        if(lastName.getText().equals("Last Name"))
        {
            lastName.setText(null);
            lastName.requestFocus();
            //remove placeholder style
            removePlaceHolderStyle(lastName);
        }
    }//GEN-LAST:event_lastNameFocusGained

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        if(email.getText().equals("Email"))
        {
            email.setText(null);
            email.requestFocus();
            //remove placeholder style
            removePlaceHolderStyle(email);
        }
    }//GEN-LAST:event_emailFocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        if(password.getText().equals("Password"))
        {
            password.setText(null);
            password.requestFocus();
            //set password character
            password.setEchoChar('\u2022');
            //remove placeholder style
            removePlaceHolderStyle(password);
        }
    }//GEN-LAST:event_passwordFocusGained

    private void idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusGained
        if(id.getText().equals("National ID"))
        {
            id.setText(null);
            id.requestFocus();
            //remove placeholder style
            removePlaceHolderStyle(id);
        }
    }//GEN-LAST:event_idFocusGained

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        if(address.getText().equals("Address"))
        {
            address.setText(null);
            address.requestFocus();
            //remove placeholder style
            removePlaceHolderStyle(address);
        }
    }//GEN-LAST:event_addressFocusGained

    private void phoneNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberFocusGained
        if(phoneNumber.getText().equals("Phone Number"))
        {
            phoneNumber.setText(null);
            phoneNumber.requestFocus();
            //remove placeholder style
            removePlaceHolderStyle(phoneNumber);
        }
    }//GEN-LAST:event_phoneNumberFocusGained

    private void firstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusLost
        if(firstName.getText().length() == 0)
        {
           //add placeholder style
           addPlaceHolderStyle(firstName);
           firstName.setText("First Name");
        }
    }//GEN-LAST:event_firstNameFocusLost

    private void lastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusLost
        if(lastName.getText().length() == 0)
        {
           //add placeholder style
           addPlaceHolderStyle(lastName);
           lastName.setText("Last Name");
        }
    }//GEN-LAST:event_lastNameFocusLost

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        if(email.getText().length() == 0)
        {
           //add placeholder style
           addPlaceHolderStyle(email);
           email.setText("Email");
        }
    }//GEN-LAST:event_emailFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        if(password.getText().length() == 0)
        {
           //add placeholder style
           addPlaceHolderStyle(password);
           password.setText("Password");
           password.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_passwordFocusLost

    private void idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusLost
        if(id.getText().length() == 0)
        {
           //add placeholder style
           addPlaceHolderStyle(id);
           id.setText("National ID");
        }
    }//GEN-LAST:event_idFocusLost

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        if(address.getText().length() == 0)
        {
           //add placeholder style
           addPlaceHolderStyle(address);
           address.setText("Address");
        }
    }//GEN-LAST:event_addressFocusLost

    private void phoneNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberFocusLost
        if(phoneNumber.getText().length() == 0)
        {
           //add placeholder style
           addPlaceHolderStyle(phoneNumber);
           phoneNumber.setText("Phone Number");
        }
    }//GEN-LAST:event_phoneNumberFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OPTAregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OPTAregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OPTAregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OPTAregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OPTAregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JLabel backSign;
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    private javax.swing.JLabel customer;
    private javax.swing.JTextField email;
    private javax.swing.JLabel errEmail;
    private javax.swing.JLabel errID;
    private javax.swing.JLabel errM;
    private javax.swing.JLabel errPass;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField id;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lock;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel min;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JLabel registerBtn;
    private javax.swing.JLabel registerBtnNav;
    private javax.swing.JLabel sep;
    private javax.swing.JLabel sep1;
    private javax.swing.JLabel sep2;
    private javax.swing.JLabel sep3;
    private javax.swing.JLabel sep4;
    private javax.swing.JLabel sep5;
    private javax.swing.JLabel sep6;
    private javax.swing.JLabel signBtnNav;
    // End of variables declaration//GEN-END:variables
}
